// angular-app/src/app/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TestComponent } from "./test/test.component";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule, TestComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  value = '';

  testTemplateCilck() {
    alert(this.value);
  }
}

<div>
  <input type="text" [(ngModel)]="value"/>
</div>
<div>
  current value is: {{value}}
</div>
<app-test [myTemplate]="myTemplate1">
  <span>my caption: </span>
  <button>test</button>
</app-test>

<ng-template #myTemplate1 let-counter="data">
  <h1>test template: {{counter}}</h1>
  <button [attr.data-testid]="'templateButton' + counter" (click)="testTemplateCilck()">Test My Template</button>
</ng-template>

// react-app/src/App.tsx
import './App.css';
import {useState} from "react";
import { Test } from "./Test";

function App() {
  const [value, setValue] = useState('');
  
  const handleChange: React.ChangeEventHandler = e => {
    setValue((e.target as HTMLInputElement).value);
  };

  const testTemplateCilck: React.MouseEventHandler = _ => {
    alert(value);
  }

  const myTemplate1 = (counter: number) => {
    return (<>
      <h1>test template: {counter}</h1>
      <button data-testid={'templateButton' + counter} onClick={testTemplateCilck}>Test My Template</button>
    </>)
  }
 
  return (
    <>
      <div>
        <input data-testid="input" type="text" onChange={handleChange}></input>
      </div>
      <div>
        current value is: {value}
      </div>
      <div>
        <Test myTemplate={myTemplate1}>
          <span>my caption: </span>
          <button>test</button>
        </Test>
      </div>
    </>
  )
}

export default App
