// react-app/src/Test.tsx
import { useState } from "react";

export function Test() {
    const [hidden, setHidden] = useState(false);

    return <>
        {!hidden && <div data-testid="description-text">
            <span>Hi, i am Test component</span>
        </div>}
        <button data-testid="hidden-button" onClick={() => setHidden(!hidden)}>hidden</button>
    </>
}

// vue-app/src/Test.vue
<script setup lang="ts">
import {ref} from "vue";

const hidden = ref(false);

</script>

<template>
    <div data-testid="description-text" v-if="!hidden">
        <span>Hi, i am Test component</span>
    </div>
    <button data-testid="hidden-button" @click="() => hidden = !hidden">hidden</button>
</template>
