// angular-app/src/first-page/first-page.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormsModule } from "@angular/forms";
import { TestComponent } from "../app/test/test.component";
import { StateService } from "../app/state.service";
import { RouterLink } from "@angular/router";

@Component({
  selector: 'app-first-page',
  standalone: true,
  imports: [FormsModule, TestComponent, RouterLink],
  templateUrl: './first-page.component.html',
  styleUrls: ['./first-page.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FirstPageComponent {
  value = '';

  constructor(private stateService: StateService) { }

  testTemplateCilck() {
    alert(this.value);
  }

  addCounter() {
    this.stateService.setCounter(this.stateService.counterValue + 1);
  }
}

<div>
  <input type="text" [(ngModel)]="value"/>
</div>
<div>
  current value is: {{value}}
</div>
<app-test [myTemplate]="myTemplate1">
  <span>my caption: </span>
  <button data-testid="testButton" (click)="addCounter()">test</button>
</app-test>

<ng-template #myTemplate1 let-counter="data">
  <h1>test template: {{counter}}</h1>
  <button [attr.data-testid]="'templateButton' + counter" (click)="testTemplateCilck()">Test My Template</button>
</ng-template>

<a routerLink="/new-page" >next page</a>

// react-app/src/pages/FirstPage.tsx
import { useState } from "react";
import { Test } from "../Test";
import { useDispatch } from "react-redux";
import { increase } from "../state/slice/counter-slice";

export default function FirstPage() {
  const [value, setValue] = useState('');
  const dispatch = useDispatch();

  console.log("first page render");
  
  const handleChange: React.ChangeEventHandler = e => {
    setValue((e.target as HTMLInputElement).value);
  };

  const testTemplateCilck: React.MouseEventHandler = _ => {
    alert(value);
  }

  const myTemplate1 = (counter: number) => {
    return (<>
      <h1>test template: {counter}</h1>
      <button data-testid={'templateButton' + counter} onClick={testTemplateCilck}>Test My Template</button>
    </>)
  }

  const addCounter = () => {
    dispatch(increase(1));
  }
  
  return (
    <>
      <div>
        <input data-testid="input" type="text" onChange={handleChange}></input>
      </div>
      <div>
        current value is: {value}
      </div>
      <div>
        <Test myTemplate={myTemplate1}>
          <span>my caption: </span>
          <button onClick={addCounter}>test</button>
        </Test>
      </div>
    </>
  )
}
